### ISSUE TITLE
Command not found: trec_eval

### ISSUE THREAD

**Issue by acohan** [joaopalotti/trec_tools#2]
It seems the NIST `trec_eval` executable is not installed through `pip install trectools`
```
    656             except OSError as e:
    657                 if e.errno == errno.ENOENT:
--> 658                     raise ValueError('Command not found: %s' % self.args[0])
    659             except Exception as e:  #pragma: no cover
    660                 logger.exception('Popen call failed: %s: %s', type(e), e)

ValueError: Command not found: trec_eval
```

**Comment by acohan** [comment]
The problem was that the script expects `trec_eval` executable in the path. 
This information is missing in the README file.

**Comment by joaopalotti** [comment]
Thanks for using our package and reporting this problem, Arman.
I have actually implemented most of the trec_eval evaluation measures locally, which eliminates the use of trec_eval. However, I have not had the chance to commit this yet. It is likely to be committed sometime during this summer.

**Comment by joaopalotti** [comment]
H @acohan,

You can pull the latest version of trectools. Hope everything from trec_eval that you need is already implemented.

Cheers,

Joao
