### ISSUE TITLE
Bump supported Terrier version

### ISSUE THREAD

**Issue by cmacdonald** [joaopalotti/trec_tools#3]
Hi,

Your command match Terrier v4 (which Terrier 5 and 5.1 also support). I'm happy to provide input about changing the commandline incantations for Terrier v5.

Craig

**Comment by joaopalotti** [comment]
Dear Craig,

I'm happy to implement / get pull requests to support Terrier v5. Please let me know what we could change.

Best,

Joao

**Comment by cmacdonald** [comment]
See PR #5 

It occurs to me it would be helpful if Terrier's batch retrieval could also write run files to stdout.

Craig

**Comment by joaopalotti** [comment]
Thanks for the modifications, Craig.
