### ISSUE TITLE
What is Robust03?

### ISSUE THREAD

**Issue by amallia** [joaopalotti/trec_tools#7]
Could you clarify which one is Robust03? 
I only know Robust04 (disk4-5 without `cr` folder) and Robust05 (AQUAINT)

**Comment by joaopalotti** [comment]
Hey Antorino,

By Robust03, I meant the [Robust track from TREC 2003 (TREC12)](https://trec.nist.gov/pubs/trec12/papers/ROBUST.OVERVIEW.pdf).

The participant runs can be found at: https://trec.nist.gov/results/trec12/robust.input.html
The relevance assessments are at https://trec.nist.gov/data/qrels_eng/
The data collection was disk4-5 without cr folder.

**Comment by amallia** [comment]
Thanks for clarifying it!
